### ISSUE TITLE
Syntax Error Python 3.10

### ISSUE THREAD

**Issue by krishnavelu** [EliAndrewC/protlib#2]
Getting syntax error while importing protlib in python 3.10, Python 3.9 is ok.
Look at the screenshot for details.

![image](https://user-images.githubusercontent.com/38440742/161732716-6cf8e675-2a55-445d-b31c-8da88233e1aa.png)

![image](https://user-images.githubusercontent.com/38440742/161732767-7bcc6733-3dec-4a4b-bf8e-ab24589a3e27.png)

Please resolve this issue.

**Comment by krishnavelu** [comment]
@EliAndrewC  This library is not maintained?

**Comment by EliAndrewC** [comment]
Ah, for some reason my email notifications on this topic were getting filtered out of my GMail inbox, so I didn't see this until Krishna helpfully emailed me today to ask about it.  (Thanks again for doing that!)

I've tested a fix locally which I will try to push out and release later tonight.

**Comment by EliAndrewC** [comment]
I've just merged https://github.com/EliAndrewC/protlib/pull/3 which should fix the issue, and uploaded a new ``1.5.0`` release to PyPI at https://pypi.org/manage/project/protlib/releases/

Thanks again for filing this.  Please let me know if you have any issues with this release - I tested on Python 3.10 myself, and all of the unit tests pass, so I think it should be working but I can roll back the release or make a new one if I missed something.

**Comment by krishnavelu** [comment]
Thank you very much @EliAndrewC
